### ISSUE TITLE
Lazy Picture/Image component

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/chusho#12]
A component that displays only when or just before entering the viewport.

**Comment by bpeab** [comment]
Can you please assign it to me ? I'll digg into it and come back we suggestions on how we could implement it if you're ok with that !

**Comment by bpeab** [comment]
Can you please assign it to me ? I'll digg into it and come back we suggestions on how we could implement it if you're ok with that !

**Comment by bpeab** [comment]
Can you please assign it to me ? I'll digg into it and come back we suggestions on how we could implement it if you're ok with that !

**Comment by LeBenLeBen** [comment]
With the growing number of browsers supporting `loading="lazy"` and precalculating the image space based on `width` and `height`, I’m wondering if this still make sense…
