### ISSUE TITLE
Inline component

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/chusho#4]
A component that wraps its children, lie them horizontally with a gap between them.

The gap should be customizable. It would probably be great to have a `wrap` prop as well.

Maybe this could be combined with the Stack component and use a prop to define the direction… Also wondering how close/redundant it would be compared to a Grid component.

**Comment by ludovicturmel** [comment]
I would be wiling to implement this feature but I agree with the last point about the redundant compared to a Grid component. Not sure to see why we would need an inline component. Do you have an usecase example ?

**Comment by LeBenLeBen** [comment]
Similar to what has been done for the `Stack`, something that automatically wraps items to add space in-between. I'm currently working on the Grid, I still have to see if I can do something to support this usecase where the "cell" doesn't have any fixed width but fit to the content. I'd rather not start on this until this question is answered.

**Comment by ludovicturmel** [comment]
Sound ok to me. Maybe a label "on hold" could be nice.

**Comment by LeBenLeBen** [comment]
Included in #19
