### ISSUE TITLE
Menu button / dropdown

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/chusho#58]
https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-actions.html
https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html

**Comment by lgollut** [comment]
Okay, just find out `useTogglable` and `useSelectable` composables. That partly answer my question above but I continue to think that `CSelectGroup` and `CSelectGroupLabel` could be more generic to be used anywhere a `role="group"` is required.

**Comment by LeBenLeBen** [comment]
To be aligned with existing components, I’d say that:

1. We need to have dedicated components for each pattern, to be able to configure them globally on their own (like there’s CSelectBtn and CCollapseBtn) but in the background, those reuse common logic by rendering a CBtn.
2. We should share the rest of the logic through composables.
3. If two components really are just the same, we can imagine abstract/extend them.

Regarding the path to make those generics, I would focus on WAI-ARIA high-level [design patterns](https://www.w3.org/TR/wai-aria-practices/examples/) rather than low-level roles such as "group".
